# Generated by Django 4.1 on 2024-11-15 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=155)),
                ('slug', models.SlugField(default='', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=155)),
                ('slug', models.SlugField(default='', max_length=155)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.city')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.URLField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=255)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.city')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeVacancy',
            fields=[
                ('open_date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('', ''), ('Legal', 'Legal'), ('Technology', 'Technology'), ('Impact', 'Impact'), ('Marketing', 'Marketing'), ('People', 'People'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Development', 'Development'), ('Supply Chain', 'Supply Chain')], default='', max_length=200)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('is_closed', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.office')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='')),
                ('title', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=155)),
                ('address', models.CharField(default='', max_length=255)),
                ('number', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('main_open_time', models.TimeField(default='05:00')),
                ('drive_open_time', models.TimeField(null=True)),
                ('main_close_time', models.TimeField(default='22:30')),
                ('drive_close_time', models.TimeField(null=True)),
                ('express_open_time', models.TimeField(null=True)),
                ('express_close_time', models.TimeField(null=True)),
                ('is_open_now', models.BooleanField(default=False)),
                ('is_has_generator', models.BooleanField(default=True)),
                ('is_has_mcdrive', models.BooleanField(default=True)),
                ('is_has_bicycle_parking', models.BooleanField(default=True)),
                ('is_has_express_window', models.BooleanField(default=False)),
                ('is_has_delivery', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cityarea')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.city')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantVacancy',
            fields=[
                ('open_date', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vacancy_title', models.CharField(default='', max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantVacancyFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('birth_date', models.DateField(default='')),
                ('phone_number', models.CharField(default='', max_length=10)),
                ('can_work_any_time', models.BooleanField(default=False)),
                ('when_can_work', models.CharField(choices=[('зранку', 'зранку'), ('вдень', 'вдень'), ('ввечері', 'ввечері'), ('вночі', 'вночі'), ('змішані години', 'змішані години')], default='зранку', max_length=100)),
                ('has_experience', models.BooleanField(default=False)),
                ('additional_info', models.TextField(default='')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.restaurantvacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=155)),
                ('image', models.URLField(default='', max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('fats', models.IntegerField(default=0)),
                ('carbonhydrates', models.IntegerField(default=0)),
                ('proteins', models.IntegerField(default=0)),
                ('sault', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('compound', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='index.menucategory')),
                ('similar_product', models.ManyToManyField(blank=True, to='index.product')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeVacancyFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=155)),
                ('cv', models.FileField(default='', upload_to='candidates/cv')),
                ('additional_info', models.TextField(default='')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.officevacancy')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.region'),
        ),
    ]
