# Generated by Django 4.1 on 2024-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alergens',
            field=models.TextField(default=''),
        ),
    ]
