# Generated by Django 4.0 on 2024-11-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_product_alergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='index.MenuCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='similar_product',
            field=models.ManyToManyField(blank=True, to='index.Product'),
        ),
    ]
