# Generated by Django 4.1 on 2024-11-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityarea',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.city'),
        ),
    ]
