# Generated by Django 4.1 on 2024-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_cityarea_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='bolt_area_image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='glovo_area_image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='has_bolt_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='has_glovo_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
