# Generated by Django 4.1 on 2024-12-06 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_city_bolt_area_image_city_glovo_area_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyMealCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HappyMealToys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.URLField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.happymealcollection')),
            ],
        ),
    ]
