# Generated by Django 4.1 on 2024-12-03 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('is_promo', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
