# Generated by Django 4.1 on 2024-12-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productsmodel',
            index=models.Index(fields=['id'], name='shop_produc_id_611652_idx'),
        ),
    ]
